---
title: "Untitled"
output: html_document
date: "2022-10-12"
---

## Initial Setup

```{r initial-setup, eval=T}
install.packages('reticulate')
reticulate::virtualenv_create('testEnv')
reticulate::use_virtualenv('testEnv')
reticulate::virtualenv_install('testEnv', packages = 'numpy')
reticulate::virtualenv_install('testEnv', packages = 'matplotlib')
reticulate::virtualenv_install('testEnv', packages = 'scipy')
```

## Setup Block
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
reticulate::use_virtualenv('testEnv')
```


## Run Python
Code from https://colorado.rstudio.com/rsc/python-visuals/python-visualization.nb.html

```{python}
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as ss
np.random.seed(0)

mu = 200
sigma = 25
x = np.random.normal(mu, sigma, size=100)

fig, (ax0, ax1) = plt.subplots(ncols=2, figsize=(8, 4))

ax0.hist(x, 20, density=1, histtype='stepfilled', facecolor='g', alpha=0.75)
ax0.set_title('stepfilled')

# Create a histogram by providing the bin edges (unequally spaced).
bins = [100, 150, 180, 195, 205, 220, 250, 300]
ax1.hist(x, bins, density=1, histtype='bar', rwidth=0.8)
ax1.set_title('unequal bins')
fig.tight_layout()
plt.show()

```
```{python}
import scipy.stats as ss
dir(ss)
```

